### ISSUE TITLE
Homework 2 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/hw-02-meganhokama#2]
Dear meganhokama -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

Great submission, your score is 9.25/10. You have until Wednesday, October 25th to resubmit for a regrade. 
---

### Exercise 1: `[10 / 10 points]`

- Plot: `[6 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: Very nice!

### Exercise 2: `[15 / 20 points]`

  - Data wrangling: `[5 / 5]`
  - Plot reproduction: `[5 / 5]`
  - Plot another country: `[5 / 5]`
  - Narrative: `[0 / 5]`
  - Feedback: I don't see your narrative. Also, fix the formatting for your subheading. It didn't work.

### Exercise 3: `[20 / 20 points]`

  - Data wrangling: `[5 / 5]`
  - Plot reproduction: `[5 / 5]`
  - Creative plot `[5 / 5]`
  - Narrative: `[5 / 5]`
  - Feedback: Great work!
  
### Exercise 4: `[10 / 10 points]`

- Plot (doesn't need to be with a `tibble()` or `tribble()`: `[5 / 5 points]`
- Approach: `[5 / 5 points]`
- Feedback: Nice work!

### Exercise 5: `[19 / 20 points]`
- Default plot: `[9 / 10]`
- Ugly plot: `[10 / 10]`

Feedback: You didn't use the default theme_gray as requested.

### Overall: `[18.5 / 20 points]`

- `[4 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- Feedback: Originally, your assignment needed to be reproduced because it wasn't working with the autograder.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[2 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- Feedback: You had some unsuppressed warnings and messages
- `[3 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- `[3 / 3]` - Reasonably sized figures.
- `[2.5 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.
- Feedback: Some of your subheadings aren't working

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by meganhokama** [comment]
Hi Dr. Chism,

Thank you for the very helpful feedback. I was able to fix some things. Appreciate your guidance~

E2: I added a narrative section.

E5: I added the theme_gray into the plot. 

Best,
Meg
